version: '3.8'
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
